<a href="https://colab.research.google.com/github/sarahajbane/Unicorn/blob/main/Data_Cleaning_with_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Cleaning**

 **Importing Libraries**

In [2]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

ValueError: mount failed

In [ ]:
!ls '/content/drive/MyDrive/Datasets'

w2d1dataset.csv  w2d2stock_prices_format.csv

In [1]:
file_path = '/content/drive/MyDrive/Datasets/w2d2stock_prices_format.csv'
stocks = pd.read_csv(file_path)

NameError: name 'pd' is not defined

In [ ]:
stocks.head()

   100000;AVGO;2014-10-27;81   51;81 9599;80  121;81  57;1497686
0   100001;AVY;2014-10-27;45   76;45   86;44   99;45  25;1289476
1   100002;AWK;2014-10-27;51   95;52    0;51   63;51   79;483967
2   100003;AXP;2014-10-27;86   01;86   75;85   76;86  63;3610616
3  100004;AYI;2014-10-27;134  99;135  78;133  77;135   63;351180
4  100005;AZO;2014-10-27;537   2;541  63;535  05;539   57;251882

In [ ]:
# Inspect the raw data
print(stocks.head())

In [ ]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   100000;AVGO;2014-10-27;81  99999 non-null  object
 1   51;81                      99999 non-null  object
 2   9599;80                    99996 non-null  object
 3   121;81                     99996 non-null  object
 4   57;1497686                 99993 non-null  object
dtypes: object(5)
memory usage: 3.8+ MB

Data Cleaning process for the above data:


1.   By adding the `header=None` parameter, we specify that the dataset does not have a header row.
Without this parameter, Pandas assumes the first row contains column names, which can lead to issues
2.  Add the `sep` Parameter:
   * The `sep` parameter specifies the delimiter used in the dataset.
   * In this case, the columns in the file are separated by a semicolon (`;`).
   * Adding `sep=';'` ensures Pandas correctly splits the data into columns.
3. Add the `na_values` Parameter:
   * the `na_values` parameter is used to identify missing value markers in the dataset.
   * Here, we have placeholde "???" as a marker for missing values and convert them to NaN.
   * This step is crucial for handling incomplete data during analysis.
4. Add the `index_col` Parameter:
   * The `index_col` parameter sets a specific column as the index of the DataFrame.
   * In this case, we use the first column (0-based index) as the index for better organization.
5. Add the `decimal` Parameter:
    * The `decimal` parameter specifies how decimal points are represented in the dataset.
    * Here, commas (`,`) are used as decimal points, so we convert them to dots (`.`) for consistency.

In [ ]:
#loading the dataset
stocks=pd.read_csv(file_path, header=None,sep=';',na_values='???', index_col=0,decimal=',')
print(stocks.head())

           1           2       3         4        5       6        7
0
100000  AVGO  2014-10-27   81.51   81.9599   80.121   81.57  1497686
100001   AVY  2014-10-27   45.76   45.8600   44.990   45.25  1289476
100002   AWK  2014-10-27   51.95   52.0000   51.630   51.79   483967
100003   AXP  2014-10-27   86.01   86.7500   85.760   86.63  3610616
100004   AYI  2014-10-27  134.99  135.7800  133.770  135.63   351180

##**Rename Columns**

Rename the columns to meaningful names for easier interpretation:

In [ ]:
stocks.columns = ["symbol","date","open","high","low","close","volume"]
print(stocks.head())

       symbol        date    open      high      low   close   volume
0
100000   AVGO  2014-10-27   81.51   81.9599   80.121   81.57  1497686
100001    AVY  2014-10-27   45.76   45.8600   44.990   45.25  1289476
100002    AWK  2014-10-27   51.95   52.0000   51.630   51.79   483967
100003    AXP  2014-10-27   86.01   86.7500   85.760   86.63  3610616
100004    AYI  2014-10-27  134.99  135.7800  133.770  135.63   351180

##**Formatting Data types**

In [ ]:
#checking the data types of the columns
stocks.dtypes

symbol     object
date       object
open      float64
high      float64
low       float64
close     float64
volume      int64
dtype: object

In [ ]:
#changing date column to datetime
stocks['date'] = pd.to_datetime(stocks['date'])
stocks.dtypes

symbol            object
date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
dtype: object

In [ ]:
stocks['volume'] = pd.to_numeric(stocks['volume'], errors='coerce')
stocks.dtypes

symbol            object
date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
dtype: object

##**Handling missing values**

In [ ]:
#This command shows the current data types of all columns in the stocks Data
stocks.isnull().sum()

symbol    0
date      0
open      6
high      3
low       3
close     0
volume    0
dtype: int64

In this step, we deal with missing values in the numerical columns: 'open', 'high', and 'low'.
* For each of these columns, we calculate the mean of the existing values and use it to fill the missing ones.

* This approach ensures that the missing data does not introduce bias while preserving the overall distribution.

Fill missing values in the 'open' column
* We use the `.fillna()` method to replace NaN values with the column's mean.
* `inplace=True` modifies the DataFrame directly without needing to reassign.

In [ ]:
stocks['open'].fillna(stocks['open'].mean())

0
100000     81.51
100001     45.76
100002     51.95
100003     86.01
100004    134.99
           ...
199995     38.43
199996     55.25
199997     98.67
199998     69.12
199999     80.45
Name: open, Length: 100000, dtype: float64

Fill missing values in the 'high' column

The same process is applied to the 'high' column.

In [ ]:
stocks['high'].fillna(stocks['high'].mean(),inplace=True)
stocks.head()

<ipython-input-27-503c23065332>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  stocks['high'].fillna(stocks['high'].mean(),inplace=True)

       symbol       date    open      high      low   close   volume
0
100000   AVGO 2014-10-27   81.51   81.9599   80.121   81.57  1497686
100001    AVY 2014-10-27   45.76   45.8600   44.990   45.25  1289476
100002    AWK 2014-10-27   51.95   52.0000   51.630   51.79   483967
100003    AXP 2014-10-27   86.01   86.7500   85.760   86.63  3610616
100004    AYI 2014-10-27  134.99  135.7800  133.770  135.63   351180

Fill missing values in the 'low' column

Finally, we handle missing values in the 'low' column.

In [ ]:
stocks['low'].fillna(stocks['low'].mean())

0
100000     80.121
100001     44.990
100002     51.630
100003     85.760
100004    133.770
           ...
199995     37.150
199996     54.400
199997     97.790
199998     68.500
199999     80.300
Name: low, Length: 100000, dtype: float64

After filling the missing values, we can check if any NaNs remain in these columns.

In [ ]:
print(stocks.isnull().sum())

symbol    0
date      0
open      6
high      0
low       3
close     0
volume    0
dtype: int64

Summarizing the Dataset After Handling Missing Values

In [ ]:
stocks.describe()

,date,open,high,low,close,volume
count,100000,99994.000000,100000.000000,99997.000000,100000.000000,1.000000e+05
mean,2015-03-24 13:43:46.848000,84.056165,84.811380,83.295330,84.076547,4.077996e+06
min,2014-10-27 00:00:00,1.620000,1.700000,1.610000,1.620000,1.000000e+02
25%,2015-01-09 00:00:00,42.800000,43.188550,42.400000,42.800000,1.033818e+06
50%,2015-03-25 00:00:00,64.990000,65.620000,64.320000,64.980000,2.011000e+06
75%,2015-06-08 00:00:00,96.070000,96.810000,95.280000,96.080000,4.149029e+06
max,2015-08-19 00:00:00,1382.610000,1395.000000,1340.100000,1351.800000,3.527019e+08
std,NaN,88.125546,88.899287,87.338695,88.138397,7.413823e+06

##**Sorting dataset**

Sorting the Dataset by the 'close' Column

In [ ]:
# Sorting the dataset
sorted_stocks = stocks.sort_values(by='close', ascending=False)

In [ ]:
sorted_stocks

       symbol       date     open     high      low    close    volume
0
195653   PCLN 2015-08-06  1351.50  1372.33  1340.10  1351.80    868814
195161   PCLN 2015-08-05  1382.61  1395.00  1325.10  1351.21   2106184
196637   PCLN 2015-08-10  1327.00  1334.00  1318.02  1323.75    549944
196145   PCLN 2015-08-07  1350.55  1350.95  1314.61  1317.35    705867
197129   PCLN 2015-08-11  1315.90  1322.60  1299.24  1307.87    513426
...       ...        ...      ...      ...      ...      ...       ...
188447    AMD 2015-07-17     1.87     1.90     1.74     1.79  28127072
191891    AMD 2015-07-28     1.62     1.77     1.62     1.77  14614569
190415    AMD 2015-07-23     1.80     1.81     1.75     1.76  10641876
190907    AMD 2015-07-24     1.76     1.77     1.65     1.67  16478376
191399    AMD 2015-07-27     1.67     1.70     1.61     1.62  11916468

[100000 rows x 7 columns]

Renaming Columns for Better Readability.
 * Column names play a crucial role in understanding the dataset.
 * By renaming the columns, we can make their purpose more explicit and intuitive

In [ ]:
stocks.rename(columns={'open': 'open_price', 'high': 'high_price', 'low': 'low_price'}, inplace=True)

In [ ]:
stocks.head()

       symbol       date  open_price  high_price  low_price   close   volume
0
100000   AVGO 2014-10-27       81.51     81.9599     80.121   81.57  1497686
100001    AVY 2014-10-27       45.76     45.8600     44.990   45.25  1289476
100002    AWK 2014-10-27       51.95     52.0000     51.630   51.79   483967
100003    AXP 2014-10-27       86.01     86.7500     85.760   86.63  3610616
100004    AYI 2014-10-27      134.99    135.7800    133.770  135.63   351180

Dropping the *'symbol'* Column:

The 'symbol' column might be unnecessary for the next analysis, so dropping it reduces data complexity and focuses on relevant information.

In [ ]:
# Dropping the 'symbol' column
stocks = stocks.drop('symbol', axis=1)

In [ ]:
stocks.head()

             date  open_price  high_price  low_price   close   volume
0
100000 2014-10-27       81.51     81.9599     80.121   81.57  1497686
100001 2014-10-27       45.76     45.8600     44.990   45.25  1289476
100002 2014-10-27       51.95     52.0000     51.630   51.79   483967
100003 2014-10-27       86.01     86.7500     85.760   86.63  3610616
100004 2014-10-27      134.99    135.7800    133.770  135.63   351180

##**Adding new column**

In [ ]:
stocks.dtypes

date          datetime64[ns]
open_price           float64
high_price           float64
low_price            float64
close                float64
volume                 int64
dtype: object

In [ ]:
# Create the 'total_value' column
stocks['total_value'] = stocks['close'] * stocks['volume']

In [ ]:
stocks.head()

,date,open_price,high_price,low_price,close,volume,total_value
0,,,,,,,
100000,2014-10-27,81.51,81.9599,80.121,81.57,1497686,1.221662e+08
100001,2014-10-27,45.76,45.8600,44.990,45.25,1289476,5.834879e+07
100002,2014-10-27,51.95,52.0000,51.630,51.79,483967,2.506465e+07
100003,2014-10-27,86.01,86.7500,85.760,86.63,3610616,3.127877e+08
100004,2014-10-27,134.99,135.7800,133.770,135.63,351180,4.763054e+07

## **Checking for duplicate rows in the entire dataset**

In [ ]:
duplicates = stocks[stocks.duplicated()]
duplicates

Empty DataFrame
Columns: [date, open_price, high_price, low_price, close, volume, total_value]
Index: []

**Thank You!**

**Keep Practicing!**